---
# define intervals and escalations
# in your Check resource
apiVersion: "crd.k8s.afrank.local/v1"
kind: Check
metadata:
  name: check-test-ping
  namespace: mozalert-stage
  labels:
    team: itse
    type: pinger
spec:
  check_interval: 1m
  retry_interval: 1m
  notification_interval: 15m
  max_attempts: 50
  image: afrank/pinger
  check_url: https://www.mozilla.org
