apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mozalert-secrets
  namespace: mozalert-stage
spec:
  backendType: gcpSecretsManager
  projectId: mozilla-it-service-engineering
  data:
    - key: itse-apps-stage-2-mozalert
      name: SENDGRID_API_KEY
      version: latest
      property: SENDGRID_API_KEY
    - key: itse-apps-stage-2-mozalert
      version: latest
      name: PROMETHEUS_GATEWAY
      property: PROMETHEUS_GATEWAY
    - key: itse-apps-stage-2-mozalert
      version: latest
      name: SLACK_DEFAULT_WEBHOOK_URL
      property: SLACK_DEFAULT_WEBHOOK_URL
    - key: itse-apps-stage-2-mozalert
      version: latest
      name: SLACK_DEFAULT_CHANNEL
      property: SLACK_DEFAULT_CHANNEL
    - key: itse-apps-stage-2-mozalert
      version: latest
      name: GCP_PROJECT
      property: GCP_PROJECT
