---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mozalert-controller
  namespace: mozalert-stage
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:main-*
spec:
  releaseName: mozalert-controller
  chart:
    git: https://github.com/mozilla-it/helm-charts
    ref: main
    path: charts/mozalert-controller
    version: 0.4.0
  values:
    image:
      repository: gcr.io/mozilla-it-service-engineering/github.com/mozilla-it/mozalert
      tag: main-87fb127ef0cde80153f429d666bd0d092a52be65
    secretRef: mozalert-secrets
